#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Jul 02, 2017 05:35:57 PM
import sys
import app1report
import os               #TO OPEN TEXT FILE
import process

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

#import test_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = New_Toplevel_1 (root)
  #  test_support.init(root, top)
    root.mainloop()

w = None
def create_New_Toplevel_1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = New_Toplevel_1 (w)
   # test_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel_1():
    global w
    w.destroy()
    w = None




class New_Toplevel_1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#d9d9d9' # X11 color: 'gray85'

        top.geometry("600x450+510+155")
        top.title("AMLP-RC")
        top.configure(background="#99cd4e")
        top.resizable(False, False)

        def commandword():
            print(v.get())
            commandword = v.get()
            process.calculate(commandword)
            #app1report.create_New_Toplevel_1(Tk(),commandword)
            os.startfile(os.getcwd()+"\\data\\report_"+str(commandword)+".dat")

        v = IntVar()

        self.Radiobutton1 = Radiobutton(top)
        self.Radiobutton1.place(relx=0.12, rely=0.09, relheight=0.06
                                , relwidth=0.11)
        self.Radiobutton1.configure(activebackground="#d9d9d9")
        self.Radiobutton1.configure(activeforeground="#000000")
        self.Radiobutton1.configure(background="#d9d9d9")
        self.Radiobutton1.configure(disabledforeground="#a3a3a3")
        self.Radiobutton1.configure(foreground="#000000")
        self.Radiobutton1.configure(highlightbackground="#d9d9d9")
        self.Radiobutton1.configure(highlightcolor="black")
        self.Radiobutton1.configure(justify=LEFT)
        self.Radiobutton1.configure(text='''DSTD1''')
        self.Radiobutton1.configure(command=commandword)
        self.Radiobutton1.configure(value='4646')
        self.Radiobutton1.configure(variable=v)

        self.Radiobutton2 = Radiobutton(top)
        self.Radiobutton2.place(relx=0.42, rely=0.09, relheight=0.06
                                , relwidth=0.11)
        self.Radiobutton2.configure(activebackground="#d9d9d9")
        self.Radiobutton2.configure(activeforeground="#000000")
        self.Radiobutton2.configure(background="#d9d9d9")
        self.Radiobutton2.configure(disabledforeground="#a3a3a3")
        self.Radiobutton2.configure(foreground="#000000")
        self.Radiobutton2.configure(highlightbackground="#d9d9d9")
        self.Radiobutton2.configure(highlightcolor="black")
        self.Radiobutton2.configure(justify=LEFT)
        self.Radiobutton2.configure(text='''DSTD2''')
        self.Radiobutton2.configure(command=commandword)
        self.Radiobutton2.configure(value='4647')
        self.Radiobutton2.configure(variable=v)

        self.Radiobutton3 = Radiobutton(top)
        self.Radiobutton3.place(relx=0.75, rely=0.09, relheight=0.06
                                , relwidth=0.11)
        self.Radiobutton3.configure(activebackground="#d9d9d9")
        self.Radiobutton3.configure(activeforeground="#000000")
        self.Radiobutton3.configure(background="#d9d9d9")
        self.Radiobutton3.configure(disabledforeground="#a3a3a3")
        self.Radiobutton3.configure(foreground="#000000")
        self.Radiobutton3.configure(highlightbackground="#d9d9d9")
        self.Radiobutton3.configure(highlightcolor="black")
        self.Radiobutton3.configure(justify=LEFT)
        self.Radiobutton3.configure(text='''DSTD3''')
        self.Radiobutton3.configure(command=commandword)
        self.Radiobutton3.configure(value='4648')
        self.Radiobutton3.configure(variable=v)

        self.Radiobutton4 = Radiobutton(top)
        self.Radiobutton4.place(relx=0.12, rely=0.27, relheight=0.06
                                , relwidth=0.11)
        self.Radiobutton4.configure(activebackground="#d9d9d9")
        self.Radiobutton4.configure(activeforeground="#000000")
        self.Radiobutton4.configure(background="#d9d9d9")
        self.Radiobutton4.configure(disabledforeground="#a3a3a3")
        self.Radiobutton4.configure(foreground="#000000")
        self.Radiobutton4.configure(highlightbackground="#d9d9d9")
        self.Radiobutton4.configure(highlightcolor="black")
        self.Radiobutton4.configure(justify=LEFT)
        self.Radiobutton4.configure(text='''DSTD4''')
        self.Radiobutton4.configure(command=commandword)
        self.Radiobutton4.configure(value='4649')
        self.Radiobutton4.configure(variable=v)

        self.Radiobutton5 = Radiobutton(top)
        self.Radiobutton5.place(relx=0.42, rely=0.27, relheight=0.06
                                , relwidth=0.1)
        self.Radiobutton5.configure(activebackground="#d9d9d9")
        self.Radiobutton5.configure(activeforeground="#000000")
        self.Radiobutton5.configure(background="#d9d9d9")
        self.Radiobutton5.configure(disabledforeground="#a3a3a3")
        self.Radiobutton5.configure(foreground="#000000")
        self.Radiobutton5.configure(highlightbackground="#d9d9d9")
        self.Radiobutton5.configure(highlightcolor="black")
        self.Radiobutton5.configure(justify=LEFT)
        self.Radiobutton5.configure(text='''LOTD''')
        self.Radiobutton5.configure(command=commandword)
        self.Radiobutton5.configure(value='4650')
        self.Radiobutton5.configure(variable=v)

        self.Radiobutton6 = Radiobutton(top)
        self.Radiobutton6.place(relx=0.75, rely=0.27, relheight=0.06
                                , relwidth=0.18)
        self.Radiobutton6.configure(activebackground="#d9d9d9")
        self.Radiobutton6.configure(activeforeground="#000000")
        self.Radiobutton6.configure(background="#d9d9d9")
        self.Radiobutton6.configure(disabledforeground="#a3a3a3")
        self.Radiobutton6.configure(foreground="#000000")
        self.Radiobutton6.configure(highlightbackground="#d9d9d9")
        self.Radiobutton6.configure(highlightcolor="black")
        self.Radiobutton6.configure(justify=LEFT)
        self.Radiobutton6.configure(text='''MSLP(TARGET)''')
        self.Radiobutton6.configure(command=commandword)
        self.Radiobutton6.configure(value='4651')
        self.Radiobutton6.configure(variable=v)

        self.Radiobutton7 = Radiobutton(top)
        self.Radiobutton7.place(relx=0.12, rely=0.47, relheight=0.06
                                , relwidth=0.19)
        self.Radiobutton7.configure(activebackground="#d9d9d9")
        self.Radiobutton7.configure(activeforeground="#000000")
        self.Radiobutton7.configure(background="#d9d9d9")
        self.Radiobutton7.configure(disabledforeground="#a3a3a3")
        self.Radiobutton7.configure(foreground="#000000")
        self.Radiobutton7.configure(highlightbackground="#d9d9d9")
        self.Radiobutton7.configure(highlightcolor="black")
        self.Radiobutton7.configure(justify=LEFT)
        self.Radiobutton7.configure(text='''HDMS(TARGET)''')
        self.Radiobutton7.configure(command=commandword)
        self.Radiobutton7.configure(value='4652')
        self.Radiobutton7.configure(variable=v)

        self.Radiobutton8 = Radiobutton(top)
        self.Radiobutton8.place(relx=0.42, rely=0.47, relheight=0.06
                                , relwidth=0.18)
        self.Radiobutton8.configure(activebackground="#d9d9d9")
        self.Radiobutton8.configure(activeforeground="#000000")
        self.Radiobutton8.configure(background="#d9d9d9")
        self.Radiobutton8.configure(disabledforeground="#a3a3a3")
        self.Radiobutton8.configure(foreground="#000000")
        self.Radiobutton8.configure(highlightbackground="#d9d9d9")
        self.Radiobutton8.configure(highlightcolor="black")
        self.Radiobutton8.configure(justify=LEFT)
        self.Radiobutton8.configure(text='''DL_SELE(DATA)''')
        self.Radiobutton8.configure(command=commandword)
        self.Radiobutton8.configure(value='4653')
        self.Radiobutton8.configure(variable=v)

        self.Radiobutton9 = Radiobutton(top)
        self.Radiobutton9.place(relx=0.75, rely=0.47, relheight=0.06
                                , relwidth=0.09)
        self.Radiobutton9.configure(activebackground="#d9d9d9")
        self.Radiobutton9.configure(activeforeground="#000000")
        self.Radiobutton9.configure(background="#d9d9d9")
        self.Radiobutton9.configure(disabledforeground="#a3a3a3")
        self.Radiobutton9.configure(foreground="#000000")
        self.Radiobutton9.configure(highlightbackground="#d9d9d9")
        self.Radiobutton9.configure(highlightcolor="black")
        self.Radiobutton9.configure(justify=LEFT)
        self.Radiobutton9.configure(text='''ACK''')
        self.Radiobutton9.configure(command=commandword)
        self.Radiobutton9.configure(value='4654')
        self.Radiobutton9.configure(variable=v)

        self.Radiobutton10 = Radiobutton(top)
        self.Radiobutton10.place(relx=0.12, rely=0.67, relheight=0.06
                                 , relwidth=0.17)
        self.Radiobutton10.configure(activebackground="#d9d9d9")
        self.Radiobutton10.configure(activeforeground="#000000")
        self.Radiobutton10.configure(background="#d9d9d9")
        self.Radiobutton10.configure(disabledforeground="#a3a3a3")
        self.Radiobutton10.configure(foreground="#000000")
        self.Radiobutton10.configure(highlightbackground="#d9d9d9")
        self.Radiobutton10.configure(highlightcolor="black")
        self.Radiobutton10.configure(justify=LEFT)
        self.Radiobutton10.configure(text='''COMMAND10''')
        self.Radiobutton10.configure(command=commandword)
        self.Radiobutton10.configure(value='4655')
        self.Radiobutton10.configure(variable=v)

        self.Radiobutton11 = Radiobutton(top)
        self.Radiobutton11.place(relx=0.42, rely=0.67, relheight=0.06
                                 , relwidth=0.17)
        self.Radiobutton11.configure(activebackground="#d9d9d9")
        self.Radiobutton11.configure(activeforeground="#000000")
        self.Radiobutton11.configure(background="#d9d9d9")
        self.Radiobutton11.configure(disabledforeground="#a3a3a3")
        self.Radiobutton11.configure(foreground="#000000")
        self.Radiobutton11.configure(highlightbackground="#d9d9d9")
        self.Radiobutton11.configure(highlightcolor="black")
        self.Radiobutton11.configure(justify=LEFT)
        self.Radiobutton11.configure(text='''COMMAND11''')
        self.Radiobutton11.configure(command=commandword)
        self.Radiobutton11.configure(value='4656')
        self.Radiobutton11.configure(variable=v)

        self.Radiobutton12 = Radiobutton(top)
        self.Radiobutton12.place(relx=0.75, rely=0.67, relheight=0.06
                                 , relwidth=0.17)
        self.Radiobutton12.configure(activebackground="#d9d9d9")
        self.Radiobutton12.configure(activeforeground="#000000")
        self.Radiobutton12.configure(background="#d9d9d9")
        self.Radiobutton12.configure(disabledforeground="#a3a3a3")
        self.Radiobutton12.configure(foreground="#000000")
        self.Radiobutton12.configure(highlightbackground="#d9d9d9")
        self.Radiobutton12.configure(highlightcolor="black")
        self.Radiobutton12.configure(justify=LEFT)
        self.Radiobutton12.configure(text='''COMMAND12''')
        self.Radiobutton12.configure(command=commandword)
        self.Radiobutton12.configure(value='4657')
        self.Radiobutton12.configure(variable=v)

        self.Radiobutton13 = Radiobutton(top)
        self.Radiobutton13.place(relx=0.12, rely=0.87, relheight=0.06
                                 , relwidth=0.17)
        self.Radiobutton13.configure(activebackground="#d9d9d9")
        self.Radiobutton13.configure(activeforeground="#000000")
        self.Radiobutton13.configure(background="#d9d9d9")
        self.Radiobutton13.configure(disabledforeground="#a3a3a3")
        self.Radiobutton13.configure(foreground="#000000")
        self.Radiobutton13.configure(highlightbackground="#d9d9d9")
        self.Radiobutton13.configure(highlightcolor="black")
        self.Radiobutton13.configure(justify=LEFT)
        self.Radiobutton13.configure(text='''COMMAND13''')
        self.Radiobutton13.configure(command=commandword)
        self.Radiobutton13.configure(value='4658')
        self.Radiobutton13.configure(variable=v)

        self.Radiobutton14 = Radiobutton(top)
        self.Radiobutton14.place(relx=0.42, rely=0.87, relheight=0.06
                                 , relwidth=0.17)
        self.Radiobutton14.configure(activebackground="#d9d9d9")
        self.Radiobutton14.configure(activeforeground="#000000")
        self.Radiobutton14.configure(background="#d9d9d9")
        self.Radiobutton14.configure(disabledforeground="#a3a3a3")
        self.Radiobutton14.configure(foreground="#000000")
        self.Radiobutton14.configure(highlightbackground="#d9d9d9")
        self.Radiobutton14.configure(highlightcolor="black")
        self.Radiobutton14.configure(justify=LEFT)
        self.Radiobutton14.configure(text='''COMMAND14''')
        self.Radiobutton14.configure(command=commandword)
        self.Radiobutton14.configure(value='4659')
        self.Radiobutton14.configure(variable=v)

        self.Radiobutton15 = Radiobutton(top)
        self.Radiobutton15.place(relx=0.75, rely=0.87, relheight=0.06
                                 , relwidth=0.17)
        self.Radiobutton15.configure(activebackground="#d9d9d9")
        self.Radiobutton15.configure(activeforeground="#000000")
        self.Radiobutton15.configure(background="#d9d9d9")
        self.Radiobutton15.configure(disabledforeground="#a3a3a3")
        self.Radiobutton15.configure(foreground="#000000")
        self.Radiobutton15.configure(highlightbackground="#d9d9d9")
        self.Radiobutton15.configure(highlightcolor="black")
        self.Radiobutton15.configure(justify=LEFT)
        self.Radiobutton15.configure(text='''COMMAND15''')
        self.Radiobutton15.configure(command=commandword)
        self.Radiobutton15.configure(value='4660')
        self.Radiobutton15.configure(variable=v)

if __name__ == '__main__':
    vp_start_gui()



