#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Jun 30, 2017 01:24:53 PM
import sys
import app1
from tkinter import filedialog
try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

#import astra_support


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = New_Toplevel_1 (root)
    #astra_support.init(root, top)

    #photo = PhotoImage(file="astra.jpg")
    #label = Label(top, image=photo)
    #background_label.place(x=0, y=0, relwidth=1, relheight=1)
    #label.pack()
    root.mainloop()

w = None





def create_New_Toplevel_1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = New_Toplevel_1 (w)
    #astra_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel_1():
    global w
    w.destroy()
    w = None

def app1filename():
    root.filename = filedialog.askopenfilename(initialdir="/", title="Select file",
                                               filetypes=(("rep files", "*.rep"), ("all files", "*.*")))
    if (root.filename != ""):
        f=open("app1repname.txt","w+")
        f.write(root.filename)
        app1.create_New_Toplevel_1(root)

def app2filename():
    root.filename = filedialog.askopenfilename(initialdir="/", title="Select file",
                                               filetypes=(("rep files", "*.rep"), ("all files", "*.*")))
    if (root.filename != ""):
        f = open("app2repname.txt", "w+")
        f.write(root.filename)
        app1.create_New_Toplevel_1(root)

def app3filename():
    root.filename = filedialog.askopenfilename(initialdir="/", title="Select file",
                                               filetypes=(("rep files", "*.rep"), ("all files", "*.*")))
    if (root.filename != ""):
        f = open("app3repname.txt", "w+")
        f.write(root.filename)
        app1.create_New_Toplevel_1(root)

class New_Toplevel_1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#d9d9d9' # X11 color: 'gray85'

        top.geometry("600x450+486+195")
        top.title("Astra Missile RCI")
        top.configure(background="#99cd4e")
        #  top.state('zoomed')
        top.resizable(False,False)
        #top.overrideredirect(1)


        self.Label1 = Label(top)
        self.Label1.place(relx=0.02, rely=0.02, height=81, width=574)
        self.Label1.configure(background="#e1e1e1")
        self.Label1.configure(disabledforeground="#4eb1ba")
        self.Label1.configure(foreground="black")
        self.Label1.configure(text='''ASTRA MISSILE''')
        self.Label1.configure(font='Times 30 bold')


        self.Button1 = Button(top)
        self.Button1.place(relx=0.4, rely=0.31, height=54, width=157)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="white")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="black")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="white")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''AMLP-RC''')
        self.Button1.configure(width=157)
        self.Button1.configure(command=app1filename)

        self.Button2 = Button(top)
        self.Button2.place(relx=0.4, rely=0.53, height=54, width=157)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="white")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="black")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''AMLP-OBC''')
        self.Button2.configure(width=157)
        self.Button2.configure(command=app2filename)

        self.Button3 = Button(top)
        self.Button3.place(relx=0.4, rely=0.73, height=54, width=157)
        self.Button3.configure(activebackground="#d9d9d9")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="white")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''MC-AMLP''')
        self.Button3.configure(width=157)
        self.Button3.configure(command=app3filename)





if __name__ == '__main__':
    vp_start_gui()



