#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Jul 02, 2017 06:02:17 PM
import sys
import callextract
import datalist

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

#import test_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = New_Toplevel_1 (root)
    #test_support.init(root, top)
    root.mainloop()

w = None


commandword="null"
def create_New_Toplevel_1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    global commandword                                       #ASSIGNING VALUUE TO GLOBAL VARIABLE COMMANDWORD
    commandword=args[0]                                      #GETTING COMMAND WORD FROM APP1
    calculate(commandword)
    #w = Toplevel (root)
    top = New_Toplevel_1 (root)
    #test_support.init(w, top, *args, **kwargs)
    return (w, top)

#FUNCTION TO FIND VALUES FROM FILE

def calculate(cw):
    file=open("app1repname.txt","r")
    repfile=""
    for a in file:
        repfile=str(a)
    callextract.extractdata(repfile)
    list=datalist.convert(commandword)
    print(list)

def destroy_New_Toplevel_1():
    global w
    w.destroy()
    w = None

#FUNCTION TO GENERATE RESULT


class New_Toplevel_1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#d9d9d9' # X11 color: 'gray85'

        top.geometry("600x450+451+164")
        top.title("Command word: "+str(commandword))
        top.configure(background="#d9d9d9")



        self.Label1 = Label(top)
        self.Label1.place(relx=0.08, rely=0.09, height=31, width=74)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text="Value is: ")
        self.Label1.configure(width=74)

        self.Message1 = Message(top)
        self.Message1.place(relx=0.22, rely=0.09, relheight=0.05, relwidth=0.1)
        self.Message1.configure(background="#d9d9d9")
        self.Message1.configure(foreground="#000000")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(text="value is  "+str(commandword))
        self.Message1.configure(width=60)






if __name__ == '__main__':
    vp_start_gui()



