#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Jul 02, 2017 05:35:57 PM
import sys
import os  # TO OPEN TEXT FILE

import app1report
import process

try:
    from Tkinter import *
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk

    py3 = 0
except ImportError:
    import tkinter.ttk as ttk

    py3 = 1


# import test_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = New_Toplevel_1(root)
    #  test_support.init(root, top)
    root.mainloop()


w = None


def create_New_Toplevel_1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel(root)
    top = New_Toplevel_1(w)
    # test_support.init(w, top, *args, **kwargs)
    return (w, top)


def destroy_New_Toplevel_1():
    global w
    w.destroy()
    w = None


class New_Toplevel_1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#d9d9d9'  # X11 color: 'gray85'

        top.geometry("600x450+510+155")
        top.title("AMLP-RC")
        top.configure(background="#99cd4e")
        #top.resizable(False, False)

        def commandword():
            print(v.get())
            commandword = v.get()
            process.calculate(commandword)
            # app1report.create_New_Toplevel_1(Tk(),commandword)
            os.startfile(os.getcwd() + "\\data1\\report_" + str(commandword) + ".dat")

        v = StringVar()

        self.Radiobutton1 = Radiobutton(top)
        self.Radiobutton1.place(relx=0.04, rely=0.09, relheight=0.06
                                , relwidth=0.11)
        self.Radiobutton1.configure(activebackground="#d9d9d9")
        self.Radiobutton1.configure(activeforeground="#000000")
        self.Radiobutton1.configure(background="#d9d9d9")
        self.Radiobutton1.configure(disabledforeground="#a3a3a3")
        self.Radiobutton1.configure(foreground="#000000")
        self.Radiobutton1.configure(highlightbackground="#d9d9d9")
        self.Radiobutton1.configure(highlightcolor="black")
        self.Radiobutton1.configure(justify=LEFT)
        self.Radiobutton1.configure(text='''DSTD1''')
        self.Radiobutton1.configure(command=commandword)
        self.Radiobutton1.configure(value='F820')
        self.Radiobutton1.configure(variable=v)

        self.Radiobutton2 = Radiobutton(top)
        self.Radiobutton2.place(relx=0.30, rely=0.09, relheight=0.06
                                , relwidth=0.11)
        self.Radiobutton2.configure(activebackground="#d9d9d9")
        self.Radiobutton2.configure(activeforeground="#000000")
        self.Radiobutton2.configure(background="#d9d9d9")
        self.Radiobutton2.configure(disabledforeground="#a3a3a3")
        self.Radiobutton2.configure(foreground="#000000")
        self.Radiobutton2.configure(highlightbackground="#d9d9d9")
        self.Radiobutton2.configure(highlightcolor="black")
        self.Radiobutton2.configure(justify=LEFT)
        self.Radiobutton2.configure(text='''DSTD2''')
        self.Radiobutton2.configure(command=commandword)
        self.Radiobutton2.configure(value='F840')
        self.Radiobutton2.configure(variable=v)

        self.Radiobutton3 = Radiobutton(top)
        self.Radiobutton3.place(relx=0.56, rely=0.09, relheight=0.06
                                , relwidth=0.11)
        self.Radiobutton3.configure(activebackground="#d9d9d9")
        self.Radiobutton3.configure(activeforeground="#000000")
        self.Radiobutton3.configure(background="#d9d9d9")
        self.Radiobutton3.configure(disabledforeground="#a3a3a3")
        self.Radiobutton3.configure(foreground="#000000")
        self.Radiobutton3.configure(highlightbackground="#d9d9d9")
        self.Radiobutton3.configure(highlightcolor="black")
        self.Radiobutton3.configure(justify=LEFT)
        self.Radiobutton3.configure(text='''DSTD3''')
        self.Radiobutton3.configure(command=commandword)
        self.Radiobutton3.configure(value='F860')
        self.Radiobutton3.configure(variable=v)

        self.Radiobutton4 = Radiobutton(top)
        self.Radiobutton4.place(relx=0.82, rely=0.09, relheight=0.06
                                , relwidth=0.11)
        self.Radiobutton4.configure(activebackground="#d9d9d9")
        self.Radiobutton4.configure(activeforeground="#000000")
        self.Radiobutton4.configure(background="#d9d9d9")
        self.Radiobutton4.configure(disabledforeground="#a3a3a3")
        self.Radiobutton4.configure(foreground="#000000")
        self.Radiobutton4.configure(highlightbackground="#d9d9d9")
        self.Radiobutton4.configure(highlightcolor="black")
        self.Radiobutton4.configure(justify=LEFT)
        self.Radiobutton4.configure(text='''DSTD4''')
        self.Radiobutton4.configure(command=commandword)
        self.Radiobutton4.configure(value='F880')
        self.Radiobutton4.configure(variable=v)

        self.Radiobutton5 = Radiobutton(top)
        self.Radiobutton5.place(relx=0.04, rely=0.23, relheight=0.06
                                , relwidth=0.11)
        self.Radiobutton5.configure(activebackground="#d9d9d9")
        self.Radiobutton5.configure(activeforeground="#000000")
        self.Radiobutton5.configure(background="#d9d9d9")
        self.Radiobutton5.configure(disabledforeground="#a3a3a3")
        self.Radiobutton5.configure(foreground="#000000")
        self.Radiobutton5.configure(highlightbackground="#d9d9d9")
        self.Radiobutton5.configure(highlightcolor="black")
        self.Radiobutton5.configure(justify=LEFT)
        self.Radiobutton5.configure(text='''LOTD''')
        self.Radiobutton5.configure(command=commandword)
        self.Radiobutton5.configure(value='F8A0')
        self.Radiobutton5.configure(variable=v)

        self.Radiobutton6 = Radiobutton(top)
        self.Radiobutton6.place(relx=0.30, rely=0.23, relheight=0.06
                                , relwidth=0.18)
        self.Radiobutton6.configure(activebackground="#d9d9d9")
        self.Radiobutton6.configure(activeforeground="#000000")
        self.Radiobutton6.configure(background="#d9d9d9")
        self.Radiobutton6.configure(disabledforeground="#a3a3a3")
        self.Radiobutton6.configure(foreground="#000000")
        self.Radiobutton6.configure(highlightbackground="#d9d9d9")
        self.Radiobutton6.configure(highlightcolor="black")
        self.Radiobutton6.configure(justify=LEFT)
        self.Radiobutton6.configure(text='''HMDS_TD-STN''')
        self.Radiobutton6.configure(command=commandword)
        self.Radiobutton6.configure(value='1234')
        self.Radiobutton6.configure(variable=v)

        self.Radiobutton7 = Radiobutton(top)
        self.Radiobutton7.place(relx=0.56, rely=0.23, relheight=0.06
                                , relwidth=0.19)
        self.Radiobutton7.configure(activebackground="#d9d9d9")
        self.Radiobutton7.configure(activeforeground="#000000")
        self.Radiobutton7.configure(background="#d9d9d9")
        self.Radiobutton7.configure(disabledforeground="#a3a3a3")
        self.Radiobutton7.configure(foreground="#000000")
        self.Radiobutton7.configure(highlightbackground="#d9d9d9")
        self.Radiobutton7.configure(highlightcolor="black")
        self.Radiobutton7.configure(justify=LEFT)
        self.Radiobutton7.configure(text='''MSLP_RT7''')
        self.Radiobutton7.configure(command=commandword)
        self.Radiobutton7.configure(value='3C20')
        self.Radiobutton7.configure(variable=v)

        self.Radiobutton8 = Radiobutton(top)
        self.Radiobutton8.place(relx=0.82, rely=0.23, relheight=0.06
                                , relwidth=0.18)
        self.Radiobutton8.configure(activebackground="#d9d9d9")
        self.Radiobutton8.configure(activeforeground="#000000")
        self.Radiobutton8.configure(background="#d9d9d9")
        self.Radiobutton8.configure(disabledforeground="#a3a3a3")
        self.Radiobutton8.configure(foreground="#000000")
        self.Radiobutton8.configure(highlightbackground="#d9d9d9")
        self.Radiobutton8.configure(highlightcolor="black")
        self.Radiobutton8.configure(justify=LEFT)
        self.Radiobutton8.configure(text='''MSLP_RT8''')
        self.Radiobutton8.configure(command=commandword)
        self.Radiobutton8.configure(value='4420')
        self.Radiobutton8.configure(variable=v)

        self.Radiobutton9 = Radiobutton(top)
        self.Radiobutton9.place(relx=0.04, rely=0.37, relheight=0.06
                                , relwidth=0.18)
        self.Radiobutton9.configure(activebackground="#d9d9d9")
        self.Radiobutton9.configure(activeforeground="#000000")
        self.Radiobutton9.configure(background="#d9d9d9")
        self.Radiobutton9.configure(disabledforeground="#a3a3a3")
        self.Radiobutton9.configure(foreground="#000000")
        self.Radiobutton9.configure(highlightbackground="#d9d9d9")
        self.Radiobutton9.configure(highlightcolor="black")
        self.Radiobutton9.configure(justify=LEFT)
        self.Radiobutton9.configure(text='''MSLP_RT9''')
        self.Radiobutton9.configure(command=commandword)
        self.Radiobutton9.configure(value='4C20')
        self.Radiobutton9.configure(variable=v)

        self.Radiobutton10 = Radiobutton(top)
        self.Radiobutton10.place(relx=0.29, rely=0.37, relheight=0.06
                                 , relwidth=0.21)
        self.Radiobutton10.configure(activebackground="#d9d9d9")
        self.Radiobutton10.configure(activeforeground="#000000")
        self.Radiobutton10.configure(background="#d9d9d9")
        self.Radiobutton10.configure(disabledforeground="#a3a3a3")
        self.Radiobutton10.configure(foreground="#000000")
        self.Radiobutton10.configure(highlightbackground="#d9d9d9")
        self.Radiobutton10.configure(highlightcolor="black")
        self.Radiobutton10.configure(justify=LEFT)
        self.Radiobutton10.configure(text='''MSLP_RT10''')
        self.Radiobutton10.configure(command=commandword)
        self.Radiobutton10.configure(value='5420')
        self.Radiobutton10.configure(variable=v)

        self.Radiobutton11 = Radiobutton(top)
        self.Radiobutton11.place(relx=0.55, rely=0.37, relheight=0.06
                                 , relwidth=0.21)
        self.Radiobutton11.configure(activebackground="#d9d9d9")
        self.Radiobutton11.configure(activeforeground="#000000")
        self.Radiobutton11.configure(background="#d9d9d9")
        self.Radiobutton11.configure(disabledforeground="#a3a3a3")
        self.Radiobutton11.configure(foreground="#000000")
        self.Radiobutton11.configure(highlightbackground="#d9d9d9")
        self.Radiobutton11.configure(highlightcolor="black")
        self.Radiobutton11.configure(justify=LEFT)
        self.Radiobutton11.configure(text='''DL_SKR_FREQ_STN7''')
        self.Radiobutton11.configure(command=commandword)
        self.Radiobutton11.configure(value='38E5')
        self.Radiobutton11.configure(variable=v)

        self.Radiobutton12 = Radiobutton(top)
        self.Radiobutton12.place(relx=0.79, rely=0.37, relheight=0.06
                                 , relwidth=0.21)
        self.Radiobutton12.configure(activebackground="#d9d9d9")
        self.Radiobutton12.configure(activeforeground="#000000")
        self.Radiobutton12.configure(background="#d9d9d9")
        self.Radiobutton12.configure(disabledforeground="#a3a3a3")
        self.Radiobutton12.configure(foreground="#000000")
        self.Radiobutton12.configure(highlightbackground="#d9d9d9")
        self.Radiobutton12.configure(highlightcolor="black")
        self.Radiobutton12.configure(justify=LEFT)
        self.Radiobutton12.configure(text='''DL_SKR_FREQ_STN8''')
        self.Radiobutton12.configure(command=commandword)
        self.Radiobutton12.configure(value='40E5')
        self.Radiobutton12.configure(variable=v)

        self.Radiobutton13 = Radiobutton(top)
        self.Radiobutton13.place(relx=0.04, rely=0.51, relheight=0.06
                                 , relwidth=0.21)
        self.Radiobutton13.configure(activebackground="#d9d9d9")
        self.Radiobutton13.configure(activeforeground="#000000")
        self.Radiobutton13.configure(background="#d9d9d9")
        self.Radiobutton13.configure(disabledforeground="#a3a3a3")
        self.Radiobutton13.configure(foreground="#000000")
        self.Radiobutton13.configure(highlightbackground="#d9d9d9")
        self.Radiobutton13.configure(highlightcolor="black")
        self.Radiobutton13.configure(justify=LEFT)
        self.Radiobutton13.configure(text='''DL_SKR_FREQ_STN9''')
        self.Radiobutton13.configure(command=commandword)
        self.Radiobutton13.configure(value='48E5')
        self.Radiobutton13.configure(variable=v)

        self.Radiobutton14 = Radiobutton(top)
        self.Radiobutton14.place(relx=0.30, rely=0.51, relheight=0.06
                                 , relwidth=0.22)
        self.Radiobutton14.configure(activebackground="#d9d9d9")
        self.Radiobutton14.configure(activeforeground="#000000")
        self.Radiobutton14.configure(background="#d9d9d9")
        self.Radiobutton14.configure(disabledforeground="#a3a3a3")
        self.Radiobutton14.configure(foreground="#000000")
        self.Radiobutton14.configure(highlightbackground="#d9d9d9")
        self.Radiobutton14.configure(highlightcolor="black")
        self.Radiobutton14.configure(justify=LEFT)
        self.Radiobutton14.configure(text='''DL_SKR_FREQ_STN10''')
        self.Radiobutton14.configure(command=commandword)
        self.Radiobutton14.configure(value='50E5')
        self.Radiobutton14.configure(variable=v)

        self.Radiobutton15 = Radiobutton(top)
        self.Radiobutton15.place(relx=0.56, rely=0.51, relheight=0.06
                                 , relwidth=0.17)
        self.Radiobutton15.configure(activebackground="#d9d9d9")
        self.Radiobutton15.configure(activeforeground="#000000")
        self.Radiobutton15.configure(background="#d9d9d9")
        self.Radiobutton15.configure(disabledforeground="#a3a3a3")
        self.Radiobutton15.configure(foreground="#000000")
        self.Radiobutton15.configure(highlightbackground="#d9d9d9")
        self.Radiobutton15.configure(highlightcolor="black")
        self.Radiobutton15.configure(justify=LEFT)
        self.Radiobutton15.configure(text='''TD_RT7''')
        self.Radiobutton15.configure(command=commandword)
        self.Radiobutton15.configure(value='3C40')
        self.Radiobutton15.configure(variable=v)

        self.Radiobutton16 = Radiobutton(top)
        self.Radiobutton16.place(relx=0.82, rely=0.51, relheight=0.06
                                 , relwidth=0.17)
        self.Radiobutton16.configure(activebackground="#d9d9d9")
        self.Radiobutton16.configure(activeforeground="#000000")
        self.Radiobutton16.configure(background="#d9d9d9")
        self.Radiobutton16.configure(disabledforeground="#a3a3a3")
        self.Radiobutton16.configure(foreground="#000000")
        self.Radiobutton16.configure(highlightbackground="#d9d9d9")
        self.Radiobutton16.configure(highlightcolor="black")
        self.Radiobutton16.configure(justify=LEFT)
        self.Radiobutton16.configure(text='''TD_RT8''')
        self.Radiobutton16.configure(command=commandword)
        self.Radiobutton16.configure(value='4440')
        self.Radiobutton16.configure(variable=v)

        self.Radiobutton17 = Radiobutton(top)
        self.Radiobutton17.place(relx=0.04, rely=0.65, relheight=0.06
                                 , relwidth=0.17)
        self.Radiobutton17.configure(activebackground="#d9d9d9")
        self.Radiobutton17.configure(activeforeground="#000000")
        self.Radiobutton17.configure(background="#d9d9d9")
        self.Radiobutton17.configure(disabledforeground="#a3a3a3")
        self.Radiobutton17.configure(foreground="#000000")
        self.Radiobutton17.configure(highlightbackground="#d9d9d9")
        self.Radiobutton17.configure(highlightcolor="black")
        self.Radiobutton17.configure(justify=LEFT)
        self.Radiobutton17.configure(text='''TD_RT9''')
        self.Radiobutton17.configure(command=commandword)
        self.Radiobutton17.configure(value='4C40')
        self.Radiobutton17.configure(variable=v)

        self.Radiobutton18 = Radiobutton(top)
        self.Radiobutton18.place(relx=0.24, rely=0.65, relheight=0.06
                                 , relwidth=0.17)
        self.Radiobutton18.configure(activebackground="#d9d9d9")
        self.Radiobutton18.configure(activeforeground="#000000")
        self.Radiobutton18.configure(background="#d9d9d9")
        self.Radiobutton18.configure(disabledforeground="#a3a3a3")
        self.Radiobutton18.configure(foreground="#000000")
        self.Radiobutton18.configure(highlightbackground="#d9d9d9")
        self.Radiobutton18.configure(highlightcolor="black")
        self.Radiobutton18.configure(justify=LEFT)
        self.Radiobutton18.configure(text='''TD_RT10''')
        self.Radiobutton18.configure(command=commandword)
        self.Radiobutton18.configure(value='5440')
        self.Radiobutton18.configure(variable=v)

        self.Radiobutton19 = Radiobutton(top)
        self.Radiobutton19.place(relx=0.45, rely=0.65, relheight=0.06
                                 , relwidth=0.26)
        self.Radiobutton19.configure(activebackground="#d9d9d9")
        self.Radiobutton19.configure(activeforeground="#000000")
        self.Radiobutton19.configure(background="#d9d9d9")
        self.Radiobutton19.configure(disabledforeground="#a3a3a3")
        self.Radiobutton19.configure(foreground="#000000")
        self.Radiobutton19.configure(highlightbackground="#d9d9d9")
        self.Radiobutton19.configure(highlightcolor="black")
        self.Radiobutton19.configure(justify=LEFT)
        self.Radiobutton19.configure(text='''DL_SKR_FREQ_ACQ_STN7''')
        self.Radiobutton19.configure(command=commandword)
        self.Radiobutton19.configure(value='3C65')
        self.Radiobutton19.configure(variable=v)

        self.Radiobutton20 = Radiobutton(top)
        self.Radiobutton20.place(relx=0.74, rely=0.65, relheight=0.06
                                 , relwidth=0.26)
        self.Radiobutton20.configure(activebackground="#d9d9d9")
        self.Radiobutton20.configure(activeforeground="#000000")
        self.Radiobutton20.configure(background="#d9d9d9")
        self.Radiobutton20.configure(disabledforeground="#a3a3a3")
        self.Radiobutton20.configure(foreground="#000000")
        self.Radiobutton20.configure(highlightbackground="#d9d9d9")
        self.Radiobutton20.configure(highlightcolor="black")
        self.Radiobutton20.configure(justify=LEFT)
        self.Radiobutton20.configure(text='''DL_SKR_FREQ_ACQ_STN8''')
        self.Radiobutton20.configure(command=commandword)
        self.Radiobutton20.configure(value='4465')
        self.Radiobutton20.configure(variable=v)

        self.Radiobutton21 = Radiobutton(top)
        self.Radiobutton21.place(relx=0.04, rely=0.79, relheight=0.06
                                 , relwidth=0.26)
        self.Radiobutton21.configure(activebackground="#d9d9d9")
        self.Radiobutton21.configure(activeforeground="#000000")
        self.Radiobutton21.configure(background="#d9d9d9")
        self.Radiobutton21.configure(disabledforeground="#a3a3a3")
        self.Radiobutton21.configure(foreground="#000000")
        self.Radiobutton21.configure(highlightbackground="#d9d9d9")
        self.Radiobutton21.configure(highlightcolor="black")
        self.Radiobutton21.configure(justify=LEFT)
        self.Radiobutton21.configure(text='''DL_SKR_FREQ_ACQ_STN9''')
        self.Radiobutton21.configure(command=commandword)
        self.Radiobutton21.configure(value='4C65')
        self.Radiobutton21.configure(variable=v)

        self.Radiobutton22 = Radiobutton(top)
        self.Radiobutton22.place(relx=0.43, rely=0.79, relheight=0.06
                                 , relwidth=0.27)
        self.Radiobutton22.configure(activebackground="#d9d9d9")
        self.Radiobutton22.configure(activeforeground="#000000")
        self.Radiobutton22.configure(background="#d9d9d9")
        self.Radiobutton22.configure(disabledforeground="#a3a3a3")
        self.Radiobutton22.configure(foreground="#000000")
        self.Radiobutton22.configure(highlightbackground="#d9d9d9")
        self.Radiobutton22.configure(highlightcolor="black")
        self.Radiobutton22.configure(justify=LEFT)
        self.Radiobutton22.configure(text='''DL_SKR_FREQ_ACQ_STN10''')
        self.Radiobutton22.configure(command=commandword)
        self.Radiobutton22.configure(value='5465')
        self.Radiobutton22.configure(variable=v)

        self.Radiobutton23 = Radiobutton(top)
        self.Radiobutton23.place(relx=0.79, rely=0.79, relheight=0.06
                                 , relwidth=0.17)
        self.Radiobutton23.configure(activebackground="#d9d9d9")
        self.Radiobutton23.configure(activeforeground="#000000")
        self.Radiobutton23.configure(background="#d9d9d9")
        self.Radiobutton23.configure(disabledforeground="#a3a3a3")
        self.Radiobutton23.configure(foreground="#000000")
        self.Radiobutton23.configure(highlightbackground="#d9d9d9")
        self.Radiobutton23.configure(highlightcolor="black")
        self.Radiobutton23.configure(justify=LEFT)
        self.Radiobutton23.configure(text='''LVRARM''')
        self.Radiobutton23.configure(command=commandword)
        self.Radiobutton23.configure(value='5204')
        self.Radiobutton23.configure(variable=v)


if __name__ == '__main__':
    vp_start_gui()
