import convertall2
def convertword(i,j):
    if i==1:
        return convertall2.hextodec(j)
    elif i==2:
        return convertall2.hextobin(j)
    elif i==3:
        return convertall2.hextomps(j)
    elif i==4:
        return convertall2.hextokmph(j)
    elif i==5:
        return convertall2.hextodec(j)
    elif i==6:
        return convertall2.hextobin(j)
    elif i==7:
        return convertall2.hextomps(j)
    elif i==8:
        return convertall2.hextokmph(j)
    elif i==9:
        return convertall2.hextodec(j)
    elif i==10:
        return convertall2.hextobin(j)
    elif i==11:
        return convertall2.hextomps(j)
    elif i==12:
        return convertall2.hextokmph(j)
    elif i==13:
        return convertall2.hextodec(j)
    elif i==14:
        return convertall2.hextobin(j)
    elif i==15:
        return convertall2.hextomps(j)
    elif i==16:
        return convertall2.hextokmph(j)
    elif i==17:
        return convertall2.hextodec(j)
    elif i==18:
        return convertall2.hextobin(j)
    elif i==19:
        return convertall2.hextomps(j)
    elif i==20:
        return convertall2.hextokmph(j)
    elif i==21:
        return convertall2.hextodec(j)
    elif i==22:
        return convertall2.hextobin(j)
    elif i==23:
        return convertall2.hextomps(j)
    elif i==24:
        return convertall2.hextokmph(j)
    elif i==25:
        return convertall2.hextodec(j)
    elif i==26:
        return convertall2.hextobin(j)
    elif i==27:
        return convertall2.hextomps(j)
    elif i==28:
        return convertall2.hextokmph(j)
    elif i==29:
        return convertall2.hextodec(j)
    elif i==30:
        return convertall2.hextobin(j)
    elif i==31:
        return convertall2.hextomps(j)
    elif i==32:
        return convertall2.hextokmph(j)